<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\modules\item\models\ItemSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Items');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="item-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create Item'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>
<?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'item_id',
            'item_id_m',
            'org_id',
            'item_number',
            'item_description',
            // 'image_file_id',
            // 'product_line',
            // 'product_line_percentage',
            // 'locator_control',
            // 'allow_negative_balance_cb',
            // 'long_description:ntext',
            // 'uom_id',
            // 'origination_type',
            // 'origination_date',
            // 'item_type',
            // 'item_status',
            // 'inventory_item_cb',
            // 'stockable_cb',
            // 'transactable_cb',
            // 'reservable_cb',
            // 'cycle_count_enabled_cb',
            // 'kit_cb',
            // 'bom_enabled_cb',
            // 'bom_type',
            // 'costing_enabled_cb',
            // 'inventory_asset_cb',
            // 'default_cost_group',
            // 'material_ac_id',
            // 'material_oh_ac_id',
            // 'overhead_ac_id',
            // 'resource_ac_id',
            // 'osp_ac_id',
            // 'expense_ac_id',
            // 'lot_uniqueness',
            // 'lot_generation',
            // 'lot_prefix',
            // 'lot_starting_number',
            // 'serial_uniqueness',
            // 'serial_generation',
            // 'serial_prefix',
            // 'serial_starting_number',
            // 'purchased_cb',
            // 'use_asl_cb',
            // 'invoice_matching',
            // 'default_buyer',
            // 'list_price',
            // 'contract_item_type',
            // 'duration_uom_id',
            // 'receipt_sub_inventory',
            // 'over_receipt_percentage',
            // 'over_receipt_action',
            // 'receipt_days_early',
            // 'receipt_days_late',
            // 'receipt_day_action',
            // 'receipt_routing',
            // 'weight_uom_id',
            // 'weight',
            // 'volume_uom_id',
            // 'volume',
            // 'dimension_uom_id',
            // 'length',
            // 'width',
            // 'height',
            // 'equipment_cb',
            // 'electronic_format_cb',
            // 'planning_method',
            // 'planner',
            // 'make_buy',
            // 'wip_supply_subinventory',
            // 'wip_supply_locator',
            // 'fix_order_quantity',
            // 'saftey_stock_days',
            // 'saftey_stock_percentage',
            // 'saftey_stock_quantity',
            // 'fix_days_supply',
            // 'fix_lot_multiplier',
            // 'minimum_order_quantity',
            // 'maximum_order_quantity',
            // 'minmax_min_quantity',
            // 'minmax_max_quantity',
            // 'minmax_multibin_number',
            // 'minmax_multibin_size',
            // 'forecast_method',
            // 'forecast_control',
            // 'demand_timefence:datetime',
            // 'planning_timefence:datetime',
            // 'release_timefence:datetime',
            // 'pre_processing_lt',
            // 'post_processing_lt',
            // 'processing_lt',
            // 'cumulative_mfg_lt',
            // 'cumulative_total_lt',
            // 'lt_lot_size',
            // 'build_in_wip_cb',
            // 'wip_supply_type',
            // 'customer_ordered_cb',
            // 'internal_ordered_cb',
            // 'shippable_cb',
            // 'returnable_cb',
            // 'invoiceable_cb',
            // 'billing_type',
            // 'service_request_cb',
            // 'atp',
            // 'picking_rule',
            // 'sourcing_rule_id',
            // 'sales_ac_id',
            // 'cogs_ac_id',
            // 'deffered_cogs_ac_id',
            // 'ip_tax_class',
            // 'op_tax_class',
            // 'ap_payment_term',
            // 'ar_payment_term',
            // 'duration',
            // 'rev_enabled_cb',
            // 'rounding_option',
            // 'onhand_with_rev_cb',
            // 'item_rev_number',
            // 'am_asset_type',
            // 'am_activity_cause',
            // 'am_activity_type',
            // 'am_activity_source',
            // 'created_by',
            // 'creation_date',
            // 'last_update_by',
            // 'last_update_date',
            // 'company_id',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>
