<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "_dates".
 *
 * @property string $d
 * @property string $aliasModel
 */
abstract class Date extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '_dates';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['d'], 'required'],
            [['d'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'd' => Yii::t('app', 'D'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\DateQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\DateQuery(get_called_class());
    }


}
