<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "_profile".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $create_time
 * @property string $update_time
 * @property string $first_name
 * @property string $last_name
 * @property string $gender
 * @property string $level
 * @property string $phone
 * @property string $mobile
 * @property integer $bill_code
 * @property string $note
 * @property string $avatar
 * @property integer $page_size
 * @property string $notifications
 * @property integer $company_id
 * @property integer $dept_id
 * @property integer $active
 * @property double $load_cost
 * @property double $seat_charge
 * @property double $daily_hours
 *
 * @property \app\modules\crud\models\User $user
 * @property string $aliasModel
 */
abstract class Profile extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '_profile';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id'], 'required'],
            [['user_id', 'bill_code', 'page_size', 'company_id', 'dept_id', 'active'], 'integer'],
            [['create_time', 'update_time'], 'safe'],
            [['note'], 'string'],
            [['load_cost', 'seat_charge', 'daily_hours'], 'number'],
            [['first_name', 'last_name', 'gender'], 'string', 'max' => 255],
            [['level'], 'string', 'max' => 2],
            [['phone', 'mobile', 'notifications'], 'string', 'max' => 12],
            [['avatar'], 'string', 'max' => 100],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'user_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_id' => Yii::t('app', 'User ID'),
            'create_time' => Yii::t('app', 'Create Time'),
            'update_time' => Yii::t('app', 'Update Time'),
            'first_name' => Yii::t('app', 'First Name'),
            'last_name' => Yii::t('app', 'Last Name'),
            'gender' => Yii::t('app', 'Gender'),
            'level' => Yii::t('app', 'Level'),
            'phone' => Yii::t('app', 'Phone'),
            'mobile' => Yii::t('app', 'Mobile'),
            'bill_code' => Yii::t('app', 'Bill Code'),
            'note' => Yii::t('app', 'Note'),
            'avatar' => Yii::t('app', 'Avatar'),
            'page_size' => Yii::t('app', 'Page Size'),
            'notifications' => Yii::t('app', 'Notifications'),
            'company_id' => Yii::t('app', 'Company ID'),
            'dept_id' => Yii::t('app', 'Dept ID'),
            'active' => Yii::t('app', 'Active'),
            'load_cost' => Yii::t('app', 'Load Cost'),
            'seat_charge' => Yii::t('app', 'Seat Charge'),
            'daily_hours' => Yii::t('app', 'Daily Hours'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\modules\crud\models\User::className(), ['user_id' => 'user_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\ProfileQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\ProfileQuery(get_called_class());
    }


}
