<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "_user_key".
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $type
 * @property string $key_value
 * @property string $create_time
 * @property string $consume_time
 * @property string $expire_time
 *
 * @property \app\modules\crud\models\User $user
 * @property string $aliasModel
 */
abstract class UserKey extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '_user_key';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'type', 'key_value'], 'required'],
            [['user_id', 'type'], 'integer'],
            [['create_time', 'consume_time', 'expire_time'], 'safe'],
            [['key_value'], 'string', 'max' => 255],
            [['key_value'], 'unique'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'user_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_id' => Yii::t('app', 'User ID'),
            'type' => Yii::t('app', 'Type'),
            'key_value' => Yii::t('app', 'Key Value'),
            'create_time' => Yii::t('app', 'Create Time'),
            'consume_time' => Yii::t('app', 'Consume Time'),
            'expire_time' => Yii::t('app', 'Expire Time'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\modules\crud\models\User::className(), ['user_id' => 'user_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\UserKeyQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\UserKeyQuery(get_called_class());
    }


}
